general_config:
  tag: CNN-elu-[10-3-3]-ld70-
  lr: 0.001
  weight_decay: 0.0
  checkpoint_frequency: 5
  validation_frequency: 2
  epochs: 2000
  batch_size:
    train: 64
    test: 1

model_config:
  VAE_model:
    input_size: 300
    input_dim: 1
    decoder_hidden_dim: 1
    encoder_hidden_dim: 50
    latent_size: 150
    num_LSTM_layers: 3


folders_config:
  out_dir_base: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/runs/variational-autoencoder

dataset_config:
    dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/subset
    stat_path: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/log_stats.npy

