general_config:
  tag: test_checkpoint_VRNN-
  lr: 0.01
  weight_decay: 0.0
  checkpoint_frequency: 20
  plot_frequency: 100
  epochs: 10
  batch_size:
    train: 512

model_config:
  VAE_model:
    input_size: 150
    input_dim: 13
    RNN_hidden_dim: 90
    encoder_hidden_dim: 50
    latent_size: 8
    num_LSTM_layers: 3


folders_config:
  out_dir_base: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/runs/variational-autoencoder

dataset_config:
    dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/subset
    stat_path: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/log_stats.npy
    aux_dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/HIE_Jsons
