general_config:
  tag: representation_experiment
  lr: 0.001
  weight_decay: 0.0
  checkpoint_frequency: 20
  plot_frequency: 1
  epochs: 100
  batch_size:
    train: 512

model_config:
  VAE_model:
    raw_input_size: 2400
    input_size: 150
    input_dim: 1
    RNN_hidden_dim: 10
    latent_size: 3
    num_RNN_layers: 1
    kld_beta: 50


folders_config:
  out_dir_base: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/runs/variational-autoencoder

dataset_config:
    dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/subset
    stat_path: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/log_stats.npy
    aux_dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/HIE_Jsons
