general_config:
  tag: vrnn_gauss_tests_z_allzero
  checkpoint_path: null
  lr: 0.001
  weight_decay: 0.0
  checkpoint_frequency: 20
  plot_frequency: 1
  epochs: 100
  batch_size:
    train: 512

model_config:
  VAE_model:
    raw_input_size: 2400
    input_size: 150
    input_dim: 11
    RNN_hidden_dim: 11
    latent_size: 5
    num_RNN_layers: 4
    kld_beta: 1


folders_config:
  out_dir_base: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/runs/variational-autoencoder

dataset_config:
    dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/subset
    stat_path: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/log_stats.npy
    aux_dataset_dir: C:/Users/mahdi/Desktop/Mahdi-Si-Projects/AI/datasets/FHR/Json/HIE_Jsons
